# Generated by Django 5.2.11 on 2026-02-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
