# Generated by Django 5.2.11 on 2026-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipie'),
        ),
    ]
